categories: [Transcriptomics]
description: AskoR links EdgeR and AskOmics
long_description: AskoR perform DE analyses from raw counts and generates AskOmics
  compliant files
name: askor_de
owner: genouest
remote_repository_url: https://github.com/genouest/galaxy-tools/tree/master/tools/askor
homepage_url: https://github.com/askomics/askoR
